  ### Comics Index
GET http://localhost:3000/comics.json

### Comics Create
POST http://localhost:3000/comics.json
Content-Type: application/json

{
"name": "Test name",
"author": "test author",
"genre": "manga"
"price": 9.99
}

### Comics Show
GET http://localhost:3000/comics/1.json

### Comics Update
PATCH http://localhost:3000/comics/1.json
Content-Type: application/json

{
"name": "New name",
"author": "test author",
"genre": "manga"
"price": 9.99
}

### Comics Destroy
DELETE http://localhost:3000/comics/1.json

### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Vicencio Mendez",
  "email": "vicencio42@gmail.com",
  "password": "password",
  "password_confirmation": "password"
}

### api requests

https://api.myanimelist.net/v2/manga
Authorization: Bearer YOUR_TOKEN


